name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - pages 

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Установка Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Шаг 3: Установка зависимостей и сборка
    - name: Install dependencies and build
      working-directory: frontend
      run: |
        npm install
        npm run build

    # Установка переменной окружения
    - name: Set environment variables
      run: echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> $GITHUB_ENV

    # Шаг 4: Deploy на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
